before_install:
  - sudo add-apt-repository ppa:plt/racket -y
  - sudo apt-get update -q

install:
  - sudo apt-get install racket
  - sh ci/install-deps.sh

script:
  - make clean test

after_script:
  - make coverage